// DO NOT EDIT
// Generated by JFlex 1.8.1 http://jflex.de/
// source: Lexical.flex


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\1\3\22\0\1\1"+
    "\1\4\1\5\3\0\1\6\1\7\2\10\1\11\1\12"+
    "\1\10\1\12\1\13\1\14\12\15\1\0\1\10\1\16"+
    "\1\17\1\16\2\0\4\20\1\21\25\20\1\10\1\22"+
    "\1\10\1\0\1\20\1\0\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\20\1\31\1\32\1\20\1\33\1\34"+
    "\1\20\1\35\1\36\2\20\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\3\20\1\10\1\45\1\10\u0182\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\4\1\1\1\5\1\6"+
    "\1\1\1\6\1\7\1\10\1\11\12\12\1\1\1\13"+
    "\2\14\1\15\1\1\1\16\1\3\1\17\1\0\1\20"+
    "\1\0\1\10\7\12\1\21\5\12\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\0\2\20\1\0"+
    "\1\17\16\12\1\32\4\12";

  private static int [] zzUnpackAction() {
    int [] result = new int[83];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\46\0\114\0\114\0\162\0\230\0\114\0\276"+
    "\0\114\0\114\0\344\0\u010a\0\u0130\0\u0156\0\230\0\u017c"+
    "\0\u01a2\0\u01c8\0\u01ee\0\u0214\0\u023a\0\u0260\0\u0286\0\u02ac"+
    "\0\u02d2\0\u02f8\0\u031e\0\114\0\u0344\0\114\0\u036a\0\114"+
    "\0\114\0\u0390\0\u03b6\0\u03dc\0\u0402\0\114\0\u0428\0\u044e"+
    "\0\u0474\0\u049a\0\u04c0\0\u04e6\0\u050c\0\u017c\0\u0532\0\u0558"+
    "\0\u057e\0\u05a4\0\u05ca\0\114\0\114\0\114\0\114\0\114"+
    "\0\114\0\114\0\114\0\u05f0\0\114\0\u0616\0\u063c\0\u063c"+
    "\0\u0662\0\u0688\0\u06ae\0\u06d4\0\u06fa\0\u0720\0\u0746\0\u076c"+
    "\0\u0792\0\u07b8\0\u07de\0\u0804\0\u082a\0\u0850\0\u017c\0\u0876"+
    "\0\u089c\0\u08c2\0\u08e8";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[83];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\5\1\6\1\7\1\10\1\3\1\11"+
    "\2\12\1\13\1\14\1\15\1\16\1\17\2\20\1\3"+
    "\1\20\1\21\1\22\1\20\1\23\1\24\1\20\1\25"+
    "\4\20\1\26\1\20\1\27\1\20\1\30\1\31\1\32"+
    "\2\33\1\34\1\35\1\33\1\36\14\33\1\37\23\33"+
    "\50\0\1\4\62\0\1\40\34\0\1\41\54\0\1\42"+
    "\41\0\1\43\2\0\1\44\44\0\1\42\1\0\1\15"+
    "\3\0\1\45\5\0\1\45\35\0\1\46\43\0\1\20"+
    "\2\0\2\20\1\0\22\20\16\0\1\20\2\0\2\20"+
    "\1\0\13\20\1\47\1\50\5\20\16\0\1\20\2\0"+
    "\2\20\1\0\13\20\1\51\6\20\16\0\1\20\2\0"+
    "\2\20\1\0\11\20\1\52\10\20\16\0\1\20\2\0"+
    "\2\20\1\0\1\53\10\20\1\54\1\20\1\55\6\20"+
    "\16\0\1\20\2\0\2\20\1\0\5\20\1\56\4\20"+
    "\1\57\7\20\16\0\1\20\2\0\2\20\1\0\4\20"+
    "\1\60\15\20\16\0\1\20\2\0\2\20\1\0\14\20"+
    "\1\61\5\20\16\0\1\20\2\0\2\20\1\0\13\20"+
    "\1\62\6\20\16\0\1\20\2\0\2\20\1\0\6\20"+
    "\1\63\13\20\46\0\1\41\2\33\2\0\1\33\1\0"+
    "\14\33\1\0\23\33\2\0\1\34\50\0\1\64\1\0"+
    "\1\65\12\0\1\66\1\0\1\67\3\0\1\70\4\0"+
    "\1\71\1\0\1\72\1\0\1\73\21\0\1\42\3\0"+
    "\1\45\5\0\1\45\16\0\11\43\1\74\34\43\2\44"+
    "\1\75\1\76\42\44\12\0\1\77\2\0\1\100\45\0"+
    "\1\20\2\0\2\20\1\0\13\20\1\101\6\20\16\0"+
    "\1\20\2\0\2\20\1\0\4\20\1\102\15\20\16\0"+
    "\1\20\2\0\2\20\1\0\12\20\1\103\7\20\16\0"+
    "\1\20\2\0\2\20\1\0\15\20\1\104\4\20\16\0"+
    "\1\20\2\0\2\20\1\0\11\20\1\105\10\20\16\0"+
    "\1\20\2\0\2\20\1\0\13\20\1\106\6\20\16\0"+
    "\1\20\2\0\2\20\1\0\14\20\1\56\5\20\16\0"+
    "\1\20\2\0\2\20\1\0\16\20\1\56\3\20\16\0"+
    "\1\20\2\0\2\20\1\0\16\20\1\107\3\20\16\0"+
    "\1\20\2\0\2\20\1\0\17\20\1\110\2\20\16\0"+
    "\1\20\2\0\2\20\1\0\7\20\1\111\12\20\16\0"+
    "\1\20\2\0\2\20\1\0\7\20\1\112\12\20\1\0"+
    "\11\43\1\74\2\43\1\75\31\43\2\0\1\75\60\0"+
    "\1\100\45\0\1\20\2\0\2\20\1\0\11\20\1\113"+
    "\10\20\16\0\1\20\2\0\2\20\1\0\1\114\21\20"+
    "\16\0\1\20\2\0\2\20\1\0\16\20\1\115\3\20"+
    "\16\0\1\20\2\0\2\20\1\0\4\20\1\56\15\20"+
    "\16\0\1\20\2\0\2\20\1\0\15\20\1\110\4\20"+
    "\16\0\1\20\2\0\2\20\1\0\1\57\21\20\16\0"+
    "\1\20\2\0\2\20\1\0\17\20\1\116\2\20\16\0"+
    "\1\20\2\0\2\20\1\0\4\20\1\117\15\20\16\0"+
    "\1\20\2\0\2\20\1\0\3\20\1\56\16\20\16\0"+
    "\1\20\2\0\2\20\1\0\11\20\1\104\10\20\16\0"+
    "\1\20\2\0\2\20\1\0\4\20\1\120\15\20\16\0"+
    "\1\20\2\0\2\20\1\0\10\20\1\56\11\20\16\0"+
    "\1\20\2\0\2\20\1\0\7\20\1\121\12\20\16\0"+
    "\1\20\2\0\2\20\1\0\14\20\1\122\5\20\16\0"+
    "\1\20\2\0\2\20\1\0\1\122\21\20\16\0\1\20"+
    "\2\0\2\20\1\0\12\20\1\123\7\20\16\0\1\20"+
    "\2\0\2\20\1\0\12\20\1\56\7\20\16\0\1\20"+
    "\2\0\2\20\1\0\17\20\1\104\2\20\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2318];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\2\1\1\11\1\1\2\11\21\1\1\11"+
    "\1\1\1\11\1\1\2\11\1\1\1\0\1\1\1\0"+
    "\1\11\15\1\10\11\1\0\1\11\1\1\1\0\24\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[83];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
  StringBuilder string = new StringBuilder();

  public void printToken(String tokenType, String spelling, int row, int col){
    System.out.println("Type: " + tokenType);
    System.out.println("Spelling: " + spelling.trim());
    System.out.println("Row: " + row);
    System.out.println("Col: " + col);
    System.out.println();
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { printToken("Error: Unknow token", yytext(), yyline, yycolumn);
            }
            // fall through
          case 27: break;
          case 2:
            { /* ignore */
            }
            // fall through
          case 28: break;
          case 3:
            { printToken("Logical Operator", yytext(), yyline, yycolumn);
            }
            // fall through
          case 29: break;
          case 4:
            { yybegin(STRING); string.setLength(0);
            }
            // fall through
          case 30: break;
          case 5:
            { printToken("Separator", yytext(), yyline, yycolumn);
            }
            // fall through
          case 31: break;
          case 6:
            { printToken("Arithmetic Operator", yytext(), yyline, yycolumn);
            }
            // fall through
          case 32: break;
          case 7:
            { printToken("Integer", yytext(), yyline, yycolumn);
            }
            // fall through
          case 33: break;
          case 8:
            { printToken("Relational Operator", yytext(), yyline, yycolumn);
            }
            // fall through
          case 34: break;
          case 9:
            { printToken("Assignment Operator", yytext(), yyline, yycolumn);
            }
            // fall through
          case 35: break;
          case 10:
            { printToken("Identifier", yytext(), yyline, yycolumn);
            }
            // fall through
          case 36: break;
          case 11:
            { string.append( yytext() );
            }
            // fall through
          case 37: break;
          case 12:
            { printToken("Unterminated String", yytext(), yyline, yycolumn);
            }
            // fall through
          case 38: break;
          case 13:
            { yybegin(YYINITIAL); printToken("String", string.toString(), yyline, yycolumn);
            }
            // fall through
          case 39: break;
          case 14:
            { printToken("Equality Operator", yytext(), yyline, yycolumn);
            }
            // fall through
          case 40: break;
          case 15:
            { printToken("Float", yytext(), yyline, yycolumn);
            }
            // fall through
          case 41: break;
          case 16:
            { printToken("Comment", yytext(), yyline, yycolumn);
            }
            // fall through
          case 42: break;
          case 17:
            { printToken("Keyword", yytext(), yyline, yycolumn);
            }
            // fall through
          case 43: break;
          case 18:
            { string.append( '\"' );
            }
            // fall through
          case 44: break;
          case 19:
            { string.append( '\'' );
            }
            // fall through
          case 45: break;
          case 20:
            { string.append( '\\' );
            }
            // fall through
          case 46: break;
          case 21:
            { string.append( '\b' );
            }
            // fall through
          case 47: break;
          case 22:
            { string.append( '\f' );
            }
            // fall through
          case 48: break;
          case 23:
            { string.append( '\n' );
            }
            // fall through
          case 49: break;
          case 24:
            { string.append( '\r' );
            }
            // fall through
          case 50: break;
          case 25:
            { string.append( '\t' );
            }
            // fall through
          case 51: break;
          case 26:
            { printToken("Boolean", yytext(), yyline, yycolumn);
            }
            // fall through
          case 52: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java Scanner [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          // Side-effect: is encodingName valid?
          java.nio.charset.Charset.forName(encodingName);
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        Scanner scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new Scanner(reader);
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
